version: "3.5"
services:
  db:
    image: postgres:9.6
    volumes:
      - ./Database/:/docker-entrypoint-initdb.d/

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=shamsad@123
      - POSTGRES_DB=quiz
    ports:
      - "5432:5432"
    restart: always

  my_app:
    container_name: my-app-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:5000"
    restart: always
