version: "3.5"
services:
  my_app:
    container_name: my-app-container
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - overlay
    ports:
      - "8080:5000"
    restart: always
  
  
  postgres-app:
    container_name: postgres-container
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "5432:5432"
    networks:
      - overlay
    restart: always

networks:
  overlay:


